In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

# Data Cleaning

In [2]:
import numpy as np
import pandas as pd

In [3]:
df1 = pd.read_csv('df1_unclean.csv')

In [268]:
df1 = df1[['NOME', 'VALOR', 'DETALHES', 'ENDEREÇO']]

In [269]:
df1

,NOME,VALOR,DETALHES,ENDEREÇO
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",R$ 1.450,"['2 quartos ', ' 56m² ', ' 2 vagas']",Nossa Senhora de Nazaré
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",R$ 900,"['3 quartos ', ' 86m² ', ' Condomínio: R$ 1']",Neópolis
2,Alugo apartamento com 160me em Lagoa Nova e va...,R$ 4.000,"['4 quartos ', ' 160m² ', ' Condomínio: R$ 0 '...",Dix-Sept Rosado
3,Apartamento Mobiliado em Ponta Negra (internet...,R$ 1.300,"['1 quarto ', ' 35m² ', ' 1 vaga']",Ponta Negra
4,Apartamento no Corais Enseada de P. Negra,R$ 1.750,"['3 quartos ', ' 96m² ', ' Condomínio: R$ 530 ...",Ponta Negra
...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,R$ 500,['3 quartos'],Emaús
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,R$ 600,"['2 quartos ', ' 65m² ', ' 1 vaga']",Emaús
1935,Casa em nova Parnamirim,R$ 900,"['3 quartos ', ' 2 vagas']",Nova Parnamirim
1936,"Apartamento com 2 dormitórios para alugar, 551...",R$ 650,"['2 quartos ', ' 5512m² ', ' Condomínio: R$ 21...",Rosa dos Ventos
1937,Aluguel - Apartamento em Cidade Verde - Campos...,R$ 1.900,"['3 quartos ', ' 78m²']",Nova Parnamirim

In [270]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1938 entries, 0 to 1937
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NOME      1938 non-null   object
 1   VALOR     1900 non-null   object
 2   DETALHES  1912 non-null   object
 3   ENDEREÇO  1938 non-null   object
dtypes: object(4)
memory usage: 60.7+ KB

In [271]:
df1.describe()

,NOME,VALOR,DETALHES,ENDEREÇO
count,1938,1900,1912,1938
unique,1450,218,647,42
top,"Residencial Plaza 2 Quartos para Aluguel, Nova...",R$ 1.100,"['2 quartos ', ' 60m² ', ' 1 vaga']",Ponta Negra
freq,19,85,57,452

In [272]:
df1['ENDEREÇO'].unique()

array(['Nossa Senhora de Nazaré', 'Neópolis', 'Dix-Sept Rosado',
       'Ponta Negra', 'Barro Vermelho', 'Petrópolis', 'Tirol', 'Alecrim',
       'Bom Pastor', 'Capim Macio', 'Lagoa Nova', 'Felipe Camarão',
       'Candelária', 'Pitimbu', 'Cidade Alta', 'Pajuçara',
       'Nossa Senhora da Apresentação', 'Rocas', 'Planalto', 'Ribeira',
       'Cidade da Esperança', 'Areia Preta', 'Lagoa Azul', 'Potengi',
       'Praia do Meio', 'Igapó', 'Lagoa Seca', 'Nova Descoberta',
       'Redinha', 'Quintas', 'Santos Reis', 'Nova Parnamirim',
       'Parque das Árvores', 'Pium (Distrito Litoral)', 'Emaús', 'Centro',
       'Cotovelo (Distrito Litoral)', 'Monte Castelo', 'Santa Tereza',
       'Rosa dos Ventos', 'Vale do Sol', 'Nova Esperança'], dtype=object)

In [273]:
import re

In [274]:
f_quarto = lambda x: re.findall('[0-9]+ quartos?', str(x))
f_area = lambda x: re.findall('[0-9]+m²', str(x))
f_condominio = lambda x: re.findall('Condomínio: R\$\ [0-9]+', str(x))
f_vaga = lambda x: re.findall('[0-9]+ vagas?', str(x))
f_valor = lambda x: x.split()[-1] if x.split() else ''

In [275]:
df2 = pd.DataFrame()
df2['N° QUARTOS'] = list(map(f_quarto, df1['DETALHES']))
df2['ÁREA (m²)'] = list(map(f_area, df1['DETALHES']))
df2['CONDOMINIO'] = list(map(f_condominio, df1['DETALHES']))
df2['VAGAS'] = list(map(f_vaga, df1['DETALHES']))
df2['VALOR'] = list(map(f_valor, df1['VALOR'].astype(str)))
df2

       N° QUARTOS ÁREA (m²)            CONDOMINIO      VAGAS  VALOR
0     [2 quartos]    [56m²]                    []  [2 vagas]  1.450
1     [3 quartos]    [86m²]    [Condomínio: R$ 1]         []    900
2     [4 quartos]   [160m²]    [Condomínio: R$ 0]  [4 vagas]  4.000
3      [1 quarto]    [35m²]                    []   [1 vaga]  1.300
4     [3 quartos]    [96m²]  [Condomínio: R$ 530]  [2 vagas]  1.750
...           ...       ...                   ...        ...    ...
1933  [3 quartos]        []                    []         []    500
1934  [2 quartos]    [65m²]                    []   [1 vaga]    600
1935  [3 quartos]        []                    []  [2 vagas]    900
1936  [2 quartos]  [5512m²]  [Condomínio: R$ 210]   [1 vaga]    650
1937  [3 quartos]    [78m²]                    []         []  1.900

[1938 rows x 5 columns]

In [276]:
f1_quarto = lambda x: re.findall('[0-9]+', str(x))
f1_area = lambda x: re.findall('[0-9]+', str(x))
f1_condominio = lambda x: re.findall('[0-9]+', str(x))
f1_vaga = lambda x: re.findall('[0-9]+', str(x))

df3 = pd.DataFrame()
df3['N° QUARTOS'] = list(map(f1_quarto, df2['N° QUARTOS']))
df3['ÁREA (m²)'] = list(map(f1_area, df2['ÁREA (m²)']))
df3['CONDOMINIO'] = list(map(f1_condominio, df2['CONDOMINIO']))
df3['VAGAS'] = list(map(f1_vaga, df2['VAGAS']))
df3['VALOR'] = df2['VALOR']
df3[['NOME', 'ENDEREÇO']] = df1[['NOME', 'ENDEREÇO']]

In [277]:
df3

,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR,NOME,ENDEREÇO
0,[2],[56],[],[2],1.450,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré
1,[3],[86],[1],[],900,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis
2,[4],[160],[0],[4],4.000,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado
3,[1],[35],[],[1],1.300,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra
4,[3],[96],[530],[2],1.750,Apartamento no Corais Enseada de P. Negra,Ponta Negra
...,...,...,...,...,...,...,...
1933,[3],[],[],[],500,Casa para alugar no Jardim Aeroporto,Emaús
1934,[2],[65],[],[1],600,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús
1935,[3],[],[],[2],900,Casa em nova Parnamirim,Nova Parnamirim
1936,[2],[5512],[210],[1],650,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos
1937,[3],[78],[],[],1.900,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim

In [278]:
df4 = pd.DataFrame()
df4 = df3[['NOME', 'ENDEREÇO', 'N° QUARTOS', 'ÁREA (m²)', 'CONDOMINIO', 'VAGAS', 'VALOR']]
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,[2],[56],[],[2],1.450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,[3],[86],[1],[],900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,[4],[160],[0],[4],4.000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,[1],[35],[],[1],1.300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,[3],[96],[530],[2],1.750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,[3],[],[],[],500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,[2],[65],[],[1],600
1935,Casa em nova Parnamirim,Nova Parnamirim,[3],[],[],[2],900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,[2],[5512],[210],[1],650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,[3],[78],[],[],1.900

# N° Quartos

In [279]:
n = df4['N° QUARTOS'].astype(str)
def content_from_lists(n):
    lst = []
    for i in n:
        if len(i)>3:
            lst.append(i[-3])
        else:
            lst.append('') # valores vazios são interpretados como kitnets e inse-re-se 1 quarto
    lst = pd.to_numeric(lst)
    return lst
    print('The result is a list "lst": ', lst)
    
content_from_lists(n)

array([2., 3., 4., ..., 3., 2., 3.])

In [280]:
a = pd.Series(content_from_lists(n), dtype=int)
print(a)

0       2.0
1       3.0
2       4.0
3       1.0
4       3.0
       ...
1933    3.0
1934    2.0
1935    3.0
1936    2.0
1937    3.0
Length: 1938, dtype: float64

In [281]:
df4['N° QUARTOS'] = a

In [282]:
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,[56],[],[2],1.450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,[86],[1],[],900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,[160],[0],[4],4.000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,[35],[],[1],1.300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,[96],[530],[2],1.750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,[],[],[],500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,[65],[],[1],600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,[],[],[2],900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,[5512],[210],[1],650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,[78],[],[],1.900

# Área

In [290]:
lit_s = []
for i in df4['ÁREA (m²)'].to_list():
    if str(i) == '[]':
        print(0)
        lit_s.append(int(0))
    else:
        print(i[0])
        lit_s.append(int(i[0]))
lit_s = to_numeric(lit_s)

56
86
160
35
96
98
56
56
90
0
56
0
60
110
0
0
56
87
92
75
56
88
0
97
0
55
0
37
70
9
0
0
0
61
40
55
176
0
26
183
43
87
98
40
219
55
57
73
56
56
0
64
60
30
72
183
0
55
56
54
108
55
0
0
25
0
54
105
57
97
150
54
104
100
50
46
170
56
60
54
0
45
86
80
55
60
59
53
81
35
48
40
0
35
57
58
72
59
55
45
55
61
45
29
0
70
60
0
55
56
55
55
57
76
40
99
110
100
80
245
72
48
60
36
0
84
0
70
0
0
54
176
0
80
54
60
92
36
36
57
100
19
50
57
0
56
80
93
40
56
0
49
19
57
58
55
384
0
56
47
92
98
98
56
78
60
57
35
57
56
0
30
80
0
55
0
56
79
108
57
52
59
76
56
0
55
58
0
0
120
56
67
0
70
420
0
55
289
0
129
61
27
72
0
56
27
0
79
115
140
29
56
34
90
30
93
0
56
53
0
426
60
300
0
46
57
49
30
46
0
56
57
55
107
45
67
55
120
36
53
90
97
240
80
100
56
0
57
77
156
150
0
42
48
38
56
59
45
83
80
70
44
53
97
0
60
0
75
96
75
46
20
49
67
58
150
0
56
73
0
45
58
34
60
0
0
0
75
36
200
54
113
55
70
68
123
0
60
0
0
45
41
56
56
96
116
120
60
57
60
0
0
56
35
108
35
90
89
50
95
76
0
57
54
183
117
57
96
56
289
156
47
0
0
75
0
30
150
79
0
0
70
0
56
84
64
0
0
0
58
0
171
68
30
0
96
56
56
57
57
89
98
56
79
55
40
47
58
0
55
0
57
57
55
55
70
0
98
75
45
0
0
59
0
30
318
68
99
56
0
12
56
14
198
57
100
36
55
148
17
76
97
0
46
66
65
15
55
54
56
40
150
50
110
61
25
70
55
57
92
80
25
25
90
50
45
85
65
55
0
58
66
68
55
0
45
57
55
170
60
0
48
0
0
55
66
0
0
25
50
55
0
56
49
36
220
0
78
98
60
59
286
55
116
56
63
43
54
55
50
56
56
0
27
116
60
32
123
92
0
68
120
56
60
56
193
193
57
78
57
50
78
58
59
160
50
59
110
80
55
55
55
0
59
55
30
86
59
34
108
55
76
0
45
38
0
55
57
56
85
56
59
25
0
60
57
73
30
52
75
0
56
96
40
58
0
0
80
55
59
55
0
68
58
80
58
0
70
52
74
0
0
61
0
80
90
115
67
0
56
117
77
63
35
57
0
0
100
30
64
90
26
0
46
36
52
56
105
120
170
55
25
57
46
30
35
25
67
52
48
183
55
60
0
75
59
100
57
53
63
0
40
79
36
20
34
67
39
56
59
60
0
38
0
56
61
0
0
95
45
83
61
19
74
36
35
20
0
44
120
73
70
55
178
55
61
45
80
60
46
55
0
65
55
98
57
44
32
52
40
100
54
130
0
27
100
67
98
36
55
117
117
56
108
108
167
142
109
0
79
53
0
45
0
67
170
97
60
55
0
56
0
50
55
57
55
55
0
55
56
34
0
60
87
0
40
56
27
59
0
58
0
0
63
0
28
54
54
54
57
57
49
65
92
110
25
70
0
30
0
0
0
56
61
78
30
200
56
30
98
58
50
0
30
56
59
98
61
35
95
54
58
59
90
35
50
0
70
0
57
40
64
103
100
45
55
60
0
100
59
61
0
74
56
75
40
260
35
57
68
25
70
100
120
52
50
60
35
19
0
29
0
0
0
95
59
70
57
59
59
80
56
55
67
59
60
55
48
75
0
70
0
350
41
85
55
0
80
61
72
68
56
68
94
194
84
45
54
60
0
48
18
60
40
64
98
0
57
96
27
0
80
120
53
340
180
1
80
54
150
183
150
45
93
40
30
53
35
56
100
96
57
150
0
59
115
57
115
75
56
73
59
64
57
40
280
0
56
0
57
54
56
92
38
135
56
85
55
76
0
214
92
150
68
96
73
52
110
0
0
63
84
120
70
117
120
55
55
150
0
61
70
140
80
57
59
0
27
50
50
56
59
0
282
56
77
79
0
55
0
150
88
40
56
60
28
56
28
80
0
0
100
56
117
56
16
59
30
90
130
59
0
284
80
183
0
57
0
0
114
284
55
82
96
55
0
25
75
59
74
52
59
0
51
57
31
282
0
55
90
56
64
30
40
56
59
60
0
55
55
57
0
0
55
40
78
56
59
108
120
56
102
100
60
61
30
56
59
35
56
56
55
56
0
65
40
0
79
61
96
40
0
62
40
282
54
55
35
80
79
88
60
47
90
54
0
20
0
0
100
90
58
58
0
96
38
0
120
56
95
95
0
100
56
0
0
55
56
25
120
145
30
65
0
396
55
36
87
98
56
85
70
60
0
55
67
35
100
55
25
35
120
0
198
57
90
35
121
110
0
56
48
56
0
92
56
92
60
48
0
56
53
56
75
48
0
12
20
0
0
36
95
56
36
57
50
70
117
59
55
0
115
56
55
11
58
63
0
56
78
0
40
41
0
79
57
56
56
0
55
92
75
40
90
50
0
56
96
350
58
98
78
75
56
55
55
28
67
57
0
115
69
45
55
45
0
108
65
55
117
123
100
60
67
101
84
360
65
35
50
35
78
0
150
52
60
55
40
0
140
40
66
0
25
20
102
84
101
0
0
98
58
42
54
97
61
0
56
0
0
89
18
0
55
54
0
95
69
0
56
0
60
60
140
135
100
90
54
56
56
190
32
1
59
56
0
60
30
56
57
0
0
19
283
55
0
48
55
0
56
72
40
90
95
90
0
67
59
165
0
100
56
35
115
0
55
50
0
70
56
56
117
54
96
67
56
58
60
60
0
56
60
90
74
57
160
45
60
58
90
36
47
57
29
40
56
59
0
230
56
0
0
0
36
40
80
103
30
64
100
0
56
185
59
56
56
0
80
40
79
0
55
69
0
59
56
55
55
180
60
108
0
75
48
55
35
185
57
30
57
79
79
180
60
0
220
56
55
16
16
58
80
57
80
96
108
59
56
35
75
40
32
56
50
80
57
0
54
80
0
90
110
0
75
54
90
56
0
0
185
240
98
80
0
0
35
42
0
0
0
44
47
30
57
80
280
90
55
50
61
56
56
56
117
69
54
118
55
50
59
55
59
20
0
50
42
80
57
0
0
0
84
129
56
56
56
64
70
0
90
0
0
68
96
0
0
67
0
54
0
45
25
57
103
0
59
58
60
58
50
94
0
26
0
56
0
98
0
0
60
56
30
45
32
0
60
0
46
0
55
44
50
0
0
65
43
130
0
64
68
45
0
45
90
0
69
0
100
44
190
28
120
77
40
78
60
65
5512
45
0
28
46
360
56
60
0
77
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78
30
30
75
0
0
49
60
60
110
0
28
120
60
60
0
46
56
55
45
0
0
0
64
68
0
90
69
0
0
32
45
0
45
44
190
44
50
65
43
130
100
77
40
60
0
65
0
5512
78

NameError: name 'to_numeric' is not defined

In [291]:
df4['ÁREA (m²)'] = pd.Series(lit_s)

In [292]:
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,56,0,[2],1.450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,86,1,[],900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,160,0,[4],4.000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,35,0,[1],1.300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,96,530,[2],1.750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,0,0,[],500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,65,0,[1],600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,0,0,[2],900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,5512,210,[1],650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,78,0,[],1.900

# Condominio

In [285]:
lits = []
for i in df4['CONDOMINIO'].to_list():
    if str(i) == '[]':
        print(0)
        lits.append(int(0))
    else:
        print(i[0])
        lits.append(int(i[0]))
lits = to_numeric(lits)

0
1
0
0
530
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
300
0
0
0
0
0
0
0
0
440
0
0
0
0
0
0
0
0
700
80
0
415
0
0
0
0
0
0
0
0
0
0
0
0
0
0
743
800
300
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
350
0
0
0
0
0
0
0
0
350
0
0
0
0
0
60
450
600
430
0
450
0
0
440
0
0
0
0
0
0
0
0
0
0
0
400
0
700
1
0
140
1
385
0
0
0
0
0
0
0
0
0
0
1
0
0
0
250
0
0
0
0
0
0
0
0
0
265
0
0
0
390
0
0
0
300
0
0
2
0
0
0
0
0
0
1
0
0
0
60
0
0
0
0
0
0
0
0
0
0
0
300
0
0
0
0
0
0
0
0
0
0
610
0
0
0
0
0
0
1
0
0
440
0
0
0
390
0
300
0
0
0
0
0
0
0
0
0
0
0
0
0
0
200
0
0
0
390
0
0
0
0
0
350
0
580
0
0
0
500
0
0
0
0
0
0
0
0
0
0
500
0
0
0
0
605
0
0
0
0
0
0
320
0
498
0
0
450
0
0
0
500
0
0
300
0
0
0
0
0
1
0
0
1
0
1
0
0
0
0
0
0
0
685
225
0
0
550
0
586
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
60
0
60
575
0
300
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
340
0
320
0
0
0
0
0
0
0
0
0
0
0
130
0
0
106
0
0
0
0
0
0
0
300
60
0
225
0
0
0
0
0
0
0
0
0
0
0
170
0
0
0
285
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
370
0
0
0
0
335
0
0
310
420
10
1
285
0
440
0
0
0
0
0
0
0
0
0
294
0
0
0
0
0
276
0
0
0
1
0
0
0
0
100
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
0
500
605
0
0
0
0
0
0
0
325
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
550
630
530
400
470
0
0
0
0
500
0
0
250
0
242
410
360
0
450
0
0
0
0
0
0
0
0
0
0
0
0
0
240
0
0
1
0
1
50
0
0
0
0
0
0
0
0
0
0
365
370
0
650
0
0
440
0
0
690
0
0
0
0
654
0
0
0
0
0
0
0
0
420
553
0
0
0
0
0
420
800
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
750
1
1
1
0
0
0
0
0
182
0
0
0
0
370
0
0
0
0
440
0
0
0
0
0
440
0
0
0
0
0
0
0
0
0
597
0
0
0
440
0
440
0
0
0
220
190
0
0
0
0
0
0
0
0
0
0
0
650
0
100
0
500
0
1
654
1
980
0
1
330
0
0
350
0
0
0
0
0
850
870
0
395
0
0
0
0
0
0
0
0
0
0
0
182
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
80
0
0
0
0
440
0
0
1
0
0
880
0
0
0
0
0
0
0
440
0
650
0
0
0
0
1
0
0
1
0
0
0
0
0
625
0
0
0
0
480
0
440
0
0
0
0
0
1
60
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
455
0
0
0
440
0
2
0
0
0
0
0
440
0
0
420
0
0
2
0
0
270
0
150
230
0
0
130
0
0
250
380
715
0
0
0
0
0
0
1
385
218
0
0
0
990
0
0
80
70
0
0
0
660
550
581
0
0
0
730
0
1
0
0
0
0
430
0
0
0
0
290
0
0
0
420
435
0
0
0
1
1
1
0
1
0
0
0
0
0
0
0
0
450
0
0
0
0
0
0
0
0
0
0
440
0
800
0
0
0
0
0
0
0
0
530
0
0
0
100
0
0
0
0
0
350
0
0
250
0
0
0
0
0
0
670
0
0
169
0
0
0
700
0
0
0
0
0
0
0
355
0
0
655
0
446
0
0
600
0
0
162
0
350
0
0
0
430
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
360
0
300
445
0
0
1
0
680
900
0
700
0
0
440
0
0
0
0
362
0
450
0
0
0
0
0
0
0
0
160
0
530
0
0
0
0
0
550
0
0
0
0
0
0
0
0
0
0
500
554
0
0
0
0
0
0
273
0
0
0
0
700
0
135
0
306
0
0
0
650
0
0
0
1
350
0
1
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
1
1
0
0
0
550
0
0
0
0
0
348
0
0
270
280
0
0
0
0
70
0
0
80
0
0
0
0
50
480
440
348
0
0
654
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
390
0
0
0
348
0
0
550
0
0
0
0
2
0
0
0
0
0
0
0
0
280
0
0
0
0
60
0
1
0
0
1
0
0
1
800
1
0
475
0
0
0
0
0
0
0
0
510
0
0
0
0
390
1
0
540
0
0
600
545
0
0
0
0
0
0
0
0
0
0
0
365
0
0
0
0
0
0
0
160
0
0
0
420
0
0
0
800
0
650
0
410
350
350
1
550
0
0
415
0
0
650
0
0
800
0
0
1
0
0
0
0
0
0
180
0
700
720
0
0
200
0
0
0
0
640
0
730
0
0
0
0
280
0
0
0
430
530
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
548
420
0
0
1
395
150
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
162
0
0
700
312
0
0
0
0
0
500
0
0
0
0
0
0
0
0
0
0
0
0
0
0
337
0
0
0
0
400
550
150
530
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
425
0
0
0
0
0
0
300
1
0
440
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
240
0
0
0
275
350
1
0
1
650
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
180
0
0
0
230
290
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
280
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
230
290
0
0
0
0
180
0
0
0
0
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
210
0

NameError: name 'to_numeric' is not defined

In [286]:
df4['CONDOMINIO'] = pd.Series(lits)

In [287]:
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,[56],0,[2],1.450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,[86],1,[],900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,[160],0,[4],4.000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,[35],0,[1],1.300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,[96],530,[2],1.750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,[],0,[],500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,[65],0,[1],600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,[],0,[2],900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,[5512],210,[1],650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,[78],0,[],1.900

# Vagas

In [293]:
lit = []
for i in df4['VAGAS'].to_list():
    if str(i) == '[]':
        print(0)
        lit.append((0))
    else:
        print(i[0])
        lit.append((i[0]))
lit = to_numeric(lit)

2
0
4
1
2
1
1
1
2
0
1
1
1
2
1
0
1
2
2
2
1
2
1
2
1
1
1
0
1
0
1
1
2
1
1
1
3
0
1
2
1
1
2
0
2
1
1
2
1
1
1
1
0
0
0
2
0
1
1
1
2
1
1
0
0
1
1
2
1
2
2
1
2
2
1
1
4
1
2
1
1
1
2
2
1
1
1
1
1
0
1
0
1
0
1
0
2
1
1
0
0
1
1
1
0
0
1
0
1
1
1
1
2
2
1
2
2
2
1
3
0
0
1
1
2
1
0
1
1
0
0
2
1
2
1
2
2
1
1
0
2
0
1
1
0
1
2
2
1
1
0
1
0
1
0
1
4
0
1
1
1
2
2
1
1
2
1
0
1
2
1
0
2
0
1
0
1
2
2
1
1
2
2
1
1
1
1
1
1
2
1
1
1
1
4
0
1
3
1
2
1
0
2
1
1
0
1
2
1
2
2
0
1
2
1
2
1
1
1
1
4
1
3
1
1
1
1
1
1
0
1
1
1
1
1
1
0
2
1
1
0
2
2
1
2
1
0
1
1
2
3
0
1
1
1
1
1
1
1
1
1
1
1
1
0
1
0
1
2
1
1
1
1
2
1
3
1
1
2
0
0
1
0
1
1
1
0
1
1
3
1
2
1
0
1
2
0
1
0
1
0
1
1
1
2
1
1
1
1
1
1
0
1
0
2
0
2
2
1
2
2
0
1
1
2
3
1
2
1
3
2
1
0
0
1
0
0
3
2
1
2
1
1
1
2
1
1
1
1
1
1
3
1
0
0
2
1
1
2
1
2
2
1
1
2
0
1
1
1
0
0
0
1
1
1
0
1
2
2
1
0
1
1
1
0
3
2
2
1
1
1
1
0
3
1
1
0
1
2
0
1
2
2
1
1
1
1
1
1
1
1
3
0
2
1
0
0
0
1
2
2
0
0
1
1
1
2
1
1
1
1
1
1
1
2
1
1
1
1
1
1
1
2
0
0
1
0
0
0
1
0
0
0
1
1
2
0
1
1
2
1
4
1
1
1
1
1
1
1
0
1
1
0
1
1
1
1
2
2
0
1
2
1
1
1
2
2
1
1
1
1
2
1
2
4
1
2
2
1
1
1
1
2
2
0
0
1
1
1
1
1
1
1
1
1
0
1
1
1
2
1
1
0
0
1
1
2
0
1
0
0
1
2
0
1
0
1
1
1
1
0
0
2
1
2
1
1
1
1
1
1
1
1
1
1
2
2
2
0
1
3
1
1
1
1
0
0
2
0
2
2
0
1
1
0
1
1
2
2
4
1
0
1
0
1
1
1
2
1
1
2
1
1
1
1
1
3
1
1
1
0
0
2
0
0
0
2
0
1
2
1
2
0
2
1
1
1
0
2
1
1
1
1
0
0
0
0
1
1
2
2
1
1
3
1
1
1
2
1
0
1
0
2
1
2
1
1
1
1
1
1
1
1
1
1
2
1
1
1
1
3
3
1
2
2
3
2
0
1
2
1
0
1
1
2
4
2
1
1
1
1
0
0
0
1
1
1
0
1
1
0
1
1
2
1
0
2
1
1
0
1
0
0
1
1
0
1
1
1
1
1
1
1
2
1
1
0
0
0
0
0
0
1
1
1
1
2
1
0
2
1
1
0
0
1
1
2
1
1
2
1
1
1
1
1
0
1
2
1
1
0
1
2
2
0
1
1
0
2
1
1
0
1
1
1
1
3
0
1
1
2
2
2
2
1
1
1
1
0
1
0
0
0
0
1
1
1
1
1
1
2
2
1
2
1
1
1
1
2
0
2
1
4
1
2
1
0
2
1
0
1
1
1
0
3
1
1
0
1
1
1
0
1
0
1
2
1
1
2
1
1
1
2
1
3
3
1
1
1
2
2
2
2
2
0
0
1
0
1
0
2
1
1
1
1
2
2
2
2
1
2
1
1
1
0
2
0
1
2
1
1
1
1
1
3
1
2
1
1
0
2
2
2
1
2
2
1
2
0
0
1
2
2
2
1
2
1
1
3
1
1
2
2
1
1
1
1
1
1
1
1
2
1
4
1
0
2
0
1
0
2
1
0
1
1
0
1
0
1
1
0
2
2
1
1
0
1
0
2
2
1
0
4
1
2
1
1
1
1
3
4
1
1
2
1
1
0
1
1
2
1
1
0
1
1
0
4
2
1
2
2
1
1
1
2
1
1
1
1
1
1
1
1
1
0
2
1
1
2
2
2
2
2
1
1
1
2
1
1
1
2
1
2
1
0
1
2
2
0
1
1
0
1
1
4
1
1
0
1
2
2
1
1
1
1
1
1
0
1
1
2
1
1
0
2
0
0
2
1
2
2
0
2
1
1
0
1
2
0
2
2
0
0
0
3
1
1
1
2
1
1
1
1
1
1
1
1
1
1
0
1
2
0
3
1
2
1
2
2
1
1
1
2
1
1
1
0
1
1
1
1
0
1
1
1
0
0
0
0
0
1
1
1
1
1
1
2
3
1
1
1
2
1
1
0
1
1
2
1
1
1
0
1
1
2
3
2
2
0
1
2
2
0
2
1
0
1
2
4
1
2
2
2
1
1
1
0
1
1
1
2
1
0
1
1
0
2
2
1
1
1
2
1
1
2
2
3
2
0
1
1
2
4
2
1
1
1
0
0
2
1
1
0
1
1
3
2
2
1
0
1
1
1
1
2
1
1
1
1
0
2
0
1
1
1
1
1
1
0
1
2
2
1
2
1
1
2
1
0
1
2
0
1
1
1
1
0
0
1
1
0
1
1
4
1
0
1
1
1
0
1
1
2
2
2
1
1
1
1
0
1
2
0
2
1
0
1
0
2
1
1
3
1
2
1
1
1
0
1
1
1
1
2
2
1
4
1
1
1
2
1
1
1
1
1
1
1
0
3
1
2
1
1
1
1
1
2
0
1
2
0
1
3
1
1
1
2
1
1
2
1
1
1
0
1
1
1
1
3
1
2
0
1
1
1
1
3
1
0
1
3
2
3
0
1
3
1
1
0
0
1
1
1
1
1
2
1
1
1
2
1
1
1
0
1
1
0
1
2
2
1
1
2
1
1
2
1
0
0
3
4
2
2
1
0
1
1
1
1
1
0
1
1
1
2
2
1
1
0
1
1
4
1
2
1
1
2
1
1
1
1
1
0
1
0
1
2
1
0
0
1
2
1
1
1
1
1
1
0
0
0
0
1
2
1
1
2
0
1
1
0
0
1
2
0
1
2
1
1
2
2
1
0
1
1
0
2
0
0
1
1
1
1
0
0
1
2
1
1
1
1
2
1
1
1
1
4
1
1
1
1
1
1
2
0
1
0
2
1
4
0
3
2
1
0
1
1
1
1
0
1
1
2
1
1
1
2
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0
1
1
1
0
0
1
1
1
2
1
0
3
1
1
2
1
1
1
1
0
1
1
1
1
1
2
1
1
0
0
1
1
1
1
4
1
2
1
1
4
2
2
1
1
0
1
2
1
0

NameError: name 'to_numeric' is not defined

In [294]:
df4['VAGAS'] = pd.Series(lit)

In [295]:
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,56,0,2,1.450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,86,1,0,900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,160,0,4,4.000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,35,0,1,1.300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,96,530,2,1.750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,0,0,0,500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,65,0,1,600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,0,0,2,900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,5512,210,1,650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,78,0,0,1.900

# Valor

In [296]:
ltr = []
for i in df4['VALOR'].to_list():
    if i == 'nan':
        ltr.append(0)
    else:
        ltr.append(i.replace('.', ''))
ltr = pd.to_numeric(ltr)

In [297]:
ltr

array([1450,  900, 4000, ...,  900,  650, 1900], dtype=int64)

In [298]:
df4['VALOR'] = pd.Series(ltr)
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,56,0,2,1450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,86,1,0,900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,160,0,4,4000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,35,0,1,1300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,96,530,2,1750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,0,0,0,500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,65,0,1,600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,0,0,2,900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,5512,210,1,650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,78,0,0,1900

In [299]:
type(df4['VALOR'][0])

numpy.int64

In [300]:
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,56,0,2,1450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,86,1,0,900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,160,0,4,4000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,35,0,1,1300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,96,530,2,1750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,0,0,0,500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,65,0,1,600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,0,0,2,900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,5512,210,1,650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,78,0,0,1900

# Removing missing values

In [301]:
df4.isna().sum()

NOME           0
ENDEREÇO       0
N° QUARTOS    53
ÁREA (m²)      0
CONDOMINIO     0
VAGAS          0
VALOR          0
dtype: int64

In [302]:
df4['N° QUARTOS'].fillna(value=1, inplace=True)
df4.isna().sum()

NOME          0
ENDEREÇO      0
N° QUARTOS    0
ÁREA (m²)     0
CONDOMINIO    0
VAGAS         0
VALOR         0
dtype: int64

In [304]:
df4

,NOME,ENDEREÇO,N° QUARTOS,ÁREA (m²),CONDOMINIO,VAGAS,VALOR
0,"Torres Amintas Barros Residence, Lagoa Nova - ...",Nossa Senhora de Nazaré,2.0,56,0,2,1450
1,"Imperdível! Lindo Apto, 3º andar | Sombra | Re...",Neópolis,3.0,86,1,0,900
2,Alugo apartamento com 160me em Lagoa Nova e va...,Dix-Sept Rosado,4.0,160,0,4,4000
3,Apartamento Mobiliado em Ponta Negra (internet...,Ponta Negra,1.0,35,0,1,1300
4,Apartamento no Corais Enseada de P. Negra,Ponta Negra,3.0,96,530,2,1750
...,...,...,...,...,...,...,...
1933,Casa para alugar no Jardim Aeroporto,Emaús,3.0,0,0,0,500
1934,Alugo Casa Mobiliada de 2/4 sem fiador com gar...,Emaús,2.0,65,0,1,600
1935,Casa em nova Parnamirim,Nova Parnamirim,3.0,0,0,2,900
1936,"Apartamento com 2 dormitórios para alugar, 551...",Rosa dos Ventos,2.0,5512,210,1,650
1937,Aluguel - Apartamento em Cidade Verde - Campos...,Nova Parnamirim,3.0,78,0,0,1900

In [305]:
df4.to_csv('df4_cleaned.csv')

In [306]:
df4.to_excel('df4_cleaned.xlsx')